[package]
name = "fizzbuzz"
authors = ["Ian Harker"]
version = "0.1.0"
edition = "2021"
keyworks = ["fizzbuzz", "cow"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
